### ISSUE TITLE
Suggestion: Add support for brewing brews

### ISSUE THREAD

**Issue by TomLewis** [SirBlobman/CooldownsX#30]
Add support for Brews made in https://www.spigotmc.org/resources/brewery.3082/
It could be as simple as listing `brewingIDs` under the cooldown type.

```
exampleBrewing:
  cooldown: 30
  cooldown-type: POTION_THROW
  brewingIDs:
    - 123
    - 124
  amount: 2
  reset-amount: true
```
