### ISSUE TITLE
Health potions do not trigger cooldown

### ISSUE THREAD

**Issue by Parthodys** [SirBlobman/CooldownsX#35]
Using health potions does not trigger a cooldown under:
```
  cooldown-type: POTION
  potion-effect:
    - HEAL
  material:
    - SPLASH_POTION
    - LINGERING_POTION
    - POTION
```
If this cooldown is triggered by other potions, it will add a cooldown even for health potions, but using health potions never activates it. 
This would be important to fix because currently it is not possible to make an 'all-in-one' cooldown for potions, and health potions are the most important one to have a cooldown for PvP wise.

Only the POTION_THROW option seems to trigger health potion cooldowns properly, but this only applies to Splash Potions, which is not enough as players would just use normal potions then.
