### ISSUE TITLE
Potion cooldown does not apply if no effect is gained

### ISSUE THREAD

**Issue by Parthodys** [SirBlobman/CooldownsX#36]
Under cooldown-type: POTION, the cooldown is never applied if you do not gain the effect.
What this means is that you can throw potions endlessly at your friends, as long as you do not gain the effect.
It actually triggers the cooldown for the person you throw it on, but not the thrower, which makes the cooldown type unreliable and exploitable.

```
  cooldown-type: POTION
  potion-effect:
    - INCREASE_DAMAGE
    - HEAL
  material:
    - SPLASH_POTION
    - LINGERING_POTION
```
